frontend/controllers/LessonsController.php
<?php
namespace frontend\controllers;

use common\models\Articles;
use common\models\ArticlesTags;
use common\models\Categories;
use common\models\LessonsResults;
use common\models\Tags;
use common\models\User;
use common\models\UsersCategories;
use Yii;
use yii\web\Controller;

/**
 * Articles controller
 */
class LessonsController extends Controller
{

    public function actionIndex()
    {
        $articles = Articles::find()->orderBy('id DESC')->all();
        return $this->render('index', [
            'articles' => $articles
        ]);
    }

    public function actionView($id)
    {
        $article = Articles::findOne(['id' => $id]);
        $lessonResult = new LessonsResults();

        if ($lessonResult->load(Yii::$app->request->post())) {
            if (!empty($lessonResult->result_tags_array)) {
                $lessonResult->result_tags = implode(',', $lessonResult->result_tags_array);
                $lessonResult->article_id = $id;
                $lessonResult->user_id = Yii::$app->user->id;

                if ($lessonResult->save()) {
                    return $this->redirect(['lessons/result', 'id' => $lessonResult->id]);
                }
            }
        }

        return $this->render('view', [
            'tags' => $this->getArticleTags($id),
            'article' => $article
        ]);
    }
    /*
     * invalid -1
     * valid +2
     */

    public function actionResult($id)
    {
        $lessonResult = LessonsResults::findOne(['id' => $id, 'user_id' => Yii::$app->user->id]);
        if(!empty($lessonResult)) {
            $articleTags = ArticlesTags::find()
                ->where(['article_id' => $lessonResult->article_id])
                ->with('tag')
                ->asArray()
                ->all();

            $article = Articles::find()->where(['id' => $lessonResult->article_id])->one();

            $resultTagsIDs = explode(',',$lessonResult->result_tags);
            $usersTags = Tags::find()->where(['id' => $resultTagsIDs])->all();
            $validTags = [];
            $validTagIDs = [];
            $percent = 0;

            if(!empty($resultTagsIDs)) {
                foreach ($articleTags as $articleTag) {
                    if($articleTag['correct']) {
                        $validTagIDs[] = $articleTag['tag_id'];
                        $validTags[] = $articleTag['tag']['name'];
                    }
                }

                $points = 0;
                $totalPoints = count($validTagIDs) * 2;
                foreach ($resultTagsIDs as $resultTagID) {
                    if(in_array($resultTagID, $validTagIDs)) {
                        $points += 2;
                    } else {
                        $points -= 1;
                    }
                }

                $percent = ($points * 100) / $totalPoints;

            }

            return $this->render('result', [
                'userTags' => $usersTags,
                'validTags' => $validTags,
                'lessonResult' => $lessonResult,
                'percent' => $percent,
                'article' => $article
            ]);
        }
        return $this->redirect(['lessons/index']);

    }

    public function getArticleTags($articleID)
    {
        $articlesTags = ArticlesTags::find()->where(['article_id' => $articleID])->with('tag')->asArray()->all();
        $articlesTagsArray = [];

        if (!empty($articlesTags)) {
            foreach ($articlesTags as $articlesTag) {
                $articlesTagsArray[] = [
                    'id' => $articlesTag['tag']['id'],
                    'name' => $articlesTag['tag']['name']
                ];
            }
        }

        shuffle($articlesTagsArray);

        return $articlesTagsArray;

    }

}

frontend/views/lessons/index.php
<?php

/** @var $articles \common\models\Articles */
use yii\helpers\Url; ?>
<?php

/* @var $this yii\web\View */

$this->title = 'Sarcine';
?>

<h2 class="page-title">Sarcine</h2>
<div class="articles-list">
    <?php foreach ($articles as $article): ?>
        <article>
            <div class="article-image">
                <img src="http://lorempixel.com/100/100/business/<?=$article->id?>" alt="">
            </div>
            <div class="article-content">
                <div class="article-title"><?= $article->title ?></div>
                <div class="article-description">
                    <?= $article->short_description ?>
                </div>
                <div class="article-buttons">
                    <a href="<?= Url::to(['lessons/view', 'id' => $article->id]) ?>" class="btn btn-info">Alege articol</a>
                </div>
            </div>
        </article>
    <?php endforeach; ?>
</div>
<!---->
<!--<div class="col-xs-3">-->
<!--    <h2 class="page-title">Фильтр заданий</h2>-->
<!--    <div class="filter-block">-->
<!--        <div class="filter-title">Тип задания</div>-->
<!--        <div class="filter-content">-->
<!--            <ul class="nav nav-pills nav-stacked checkbox-list">-->
<!--                <li class="checked"><a href="#"><span><i class="fa fa-check"></i></span> Оценивании статьи</a></li>-->
<!--                <li><a href="#"><span><i class="fa fa-check"></i></span> Правда/ложь</a></li>-->
<!--                <li><a href="#"><span><i class="fa fa-check"></i></span> Пропаганда</a></li>-->
<!--            </ul>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="filter-block">-->
<!--        <div class="filter-title">Сложность</div>-->
<!--        <div class="filter-content">-->
<!--            <ul class="nav nav-pills nav-stacked checkbox-list checkbox-list-one">-->
<!--                <li><a href="#"><span><i class="fa fa-dot-circle-o"></i></span> Легкая</a></li>-->
<!--                <li class="checked"><a href="#"><span><i class="fa fa-dot-circle-o"></i></span> Средняя</a></li>-->
<!--                <li><a href="#"><span><i class="fa fa-dot-circle-o"></i></span> Сложная</a></li>-->
<!--            </ul>-->
<!--        </div>-->
<!--    </div>-->
<!---->
<!--</div>-->

frontend/views/lessons/result.php
<?php

/** @var $article \common\models\Articles */
/** @var $lessonResult \common\models\LessonsResults */
/** @var $percent integer */
/** @var $userTags array */
/** @var $validTags array */

$this->title = "Resultatul ".$article->title
?>

<div class="row">
    <div class="col-xs-12">
        <h2 class="page-title">Result</h2>
        <div class="lesson-body">
            result
            <pre>
                <?php print_r($percent)?>
            </pre>
            <pre>
                <?php print_r($lessonResult)?>
            </pre>
            <pre>
                <?php print_r($userTags)?>
            </pre>
            <pre>
                <?php print_r($validTags)?>
            </pre>
        </div>
    </div>
</div>

frontend/views/lessons/view.php
<?php

/** @var $article \common\models\Articles */

$this->title = $article->title;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html; ?>

<div class="row">
    <div class="col-xs-9">
        <h2 class="page-title"><?= $article->title ?></h2>
        <div class="lesson-body">
            <?= $article->text ?>
        </div>
    </div>
    <div class="col-xs-3">
        <?php if(!empty($tags)):?>
            <?php $form = ActiveForm::begin(); ?>
            <h2 class="page-title">Analiza resursei:</h2>
            <div class="filter-block form-group">
                <div class="filter-content">
                    <ul class="nav nav-pills nav-stacked checkbox-list" id="tags_list">
                        <?php foreach ($tags as $tag): ?>
                            <li>
                                <a href="#">
                                    <span><i class="fa fa-check"></i></span> <?= $tag['name'] ?>
                                    <input type="hidden" disabled name="LessonsResults[result_tags_array][]"
                                           value="<?= $tag['id'] ?>">
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
            <div class="form-group">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-success btn-block']) ?>
            </div>
            <?php ActiveForm::end(); ?>

            <button class="btn btn-primary" type="button"
                    data-toggle="collapse" data-target="#adminComment" aria-expanded="false" aria-controls="adminComment">
                <i class="fa fa-comment"></i> Comentariu
            </button>
            <div class="collapse" id="adminComment">
                <br>
                <div class="well">
                    <?=$article->comment?>
                </div>
            </div>
        <?php endif;?>
<!--        <div class="filter-block">-->
<!--            <div class="filter-title">Грамматика</div>-->
<!--            <div class="filter-content">-->
<!--                <ul class="nav nav-pills nav-stacked checkbox-list checkbox-list-one">-->
<!--                    <li><a href="#"><span><i class="fa fa-check"></i></span> Пунктуация</a></li>-->
<!--                    <li><a href="#"><span><i class="fa fa-check"></i></span> Диакритики</a></li>-->
<!--                    <li><a href="#"><span><i class="fa fa-check"></i></span> Лингвистические</a></li>-->
<!--                </ul>-->
<!--            </div>-->
<!--        </div>-->

    </div>
</div>